const API = '/api/admin';
const statusText = { pending:'Ожидает оплаты', awaiting_payment:'Ожидает оплаты', paid:'Оплачен', cancelled:'Отменён', expired:'Истёк', refunded:'Возвращён' };
async function api(url, options={}) { const response=await fetch(url,{...options,headers:{...(options.headers||{})}}); if(response.status===401){location.replace('/admin/login');throw new Error('Сессия истекла');} if(!response.ok) throw new Error('Ошибка сервера'); return response; }
function cell(text){const el=document.createElement('td');el.textContent=text;return el;}
async function loadAnalytics(){try{const data=await (await api('/api/admin/analytics')).json();const revenues=data.map(d=>(d.revenue||0)/100).reverse();const counts=data.map(d=>Number(d.orders_count||0)).reverse();document.getElementById('stat-revenue').textContent=`${revenues.reduce((a,b)=>a+b,0).toFixed(2)} ₽`;document.getElementById('stat-orders').textContent=counts.reduce((a,b)=>a+b,0);document.getElementById('stat-avg').textContent=`${(revenues.reduce((a,b)=>a+b,0)/(counts.reduce((a,b)=>a+b,0)||1)).toFixed(2)} ₽`;if(window.Chart)new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:data.map(d=>new Date(d.date).toLocaleDateString('ru-RU')).reverse(),datasets:[{label:'Выручка, ₽',data:revenues,borderColor:'#FF3D00',backgroundColor:'rgba(255,61,0,.08)',fill:true,tension:.4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});}catch(error){console.error(error);}}
async function loadProducts(){const tbody=document.getElementById('products-table');try{const products=await (await fetch('/api/products')).json();tbody.replaceChildren();if(!products.length){tbody.append(emptyRow(5,'Нет товаров'));return;}products.forEach(product=>{const row=document.createElement('tr');const photo=document.createElement('td');if(product.preview_image){const img=document.createElement('img');img.src=`/uploads/${encodeURIComponent(product.preview_image)}`;img.alt=product.title;img.width=48;img.height=48;img.loading='lazy';photo.append(img);}row.append(photo,cell(product.title),cell(`${(product.price/100).toFixed(2)} ₽`),cell(String(product.stock)));const actions=cell('');const remove=document.createElement('button');remove.className='btn btn-secondary';remove.textContent='Удалить';remove.addEventListener('click',()=>deleteProduct(product.id));actions.append(remove);row.append(actions);tbody.append(row);});}catch(error){tbody.replaceChildren(emptyRow(5,error.message));}}
function emptyRow(span,text){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=span;cell.textContent=text;cell.style.cssText='text-align:center;color:var(--muted);padding:32px';row.append(cell);return row;}
async function deleteProduct(id){if(!confirm('Удалить товар?'))return;try{await api(`/api/admin/products/${encodeURIComponent(id)}`,{method:'DELETE'});await loadProducts();}catch(error){alert(error.message);}}
async function loadOrders(){const tbody=document.getElementById('orders-table');try{const orders=await (await api('/api/admin/orders')).json();tbody.replaceChildren();if(!orders.length){tbody.append(emptyRow(5,'Нет заказов'));return;}orders.forEach(order=>{const row=document.createElement('tr');row.append(cell(`#${order.id.slice(0,8)}`),cell(order.customer_name),cell(`${(order.total_amount/100).toFixed(2)} ₽`),cell(statusText[order.status]||order.status),cell(new Date(order.created_at).toLocaleString('ru-RU')));tbody.append(row);});}catch(error){tbody.replaceChildren(emptyRow(5,error.message));}}
const modal=document.getElementById('product-modal'),dropZone=document.getElementById('drop-zone'),fileInput=document.getElementById('product-images');let selectedFiles=[];
document.getElementById('open-modal').addEventListener('click',()=>{modal.style.display='flex';selectedFiles=[];updatePreview();});document.getElementById('close-modal').addEventListener('click',()=>{modal.style.display='none';});dropZone.addEventListener('click',()=>fileInput.click());dropZone.addEventListener('dragover',event=>{event.preventDefault();dropZone.classList.add('dragover');});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('dragover'));dropZone.addEventListener('drop',event=>{event.preventDefault();dropZone.classList.remove('dragover');addFiles(event.dataTransfer.files);});fileInput.addEventListener('change',event=>addFiles(event.target.files));
function addFiles(files){const valid=[...files].filter(file=>file.type.startsWith('image/')&&file.size<=5*1024*1024);if(selectedFiles.length+valid.length>10)return alert('Максимум 10 фотографий до 5 МБ каждая');selectedFiles.push(...valid.slice(0,10-selectedFiles.length));updatePreview();}
function updatePreview(){const preview=document.getElementById('image-preview');preview.replaceChildren();selectedFiles.forEach((file,index)=>{const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt=index===0?'Основное изображение':'Изображение товара';image.onload=()=>URL.revokeObjectURL(image.src);preview.append(image);});}
document.getElementById('product-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('[type=submit]');button.disabled=true;try{const form=new FormData();form.append('title',document.getElementById('p-title').value);form.append('description',document.getElementById('p-desc').value);form.append('price',Math.round(Number(document.getElementById('p-price').value)*100));form.append('category',document.getElementById('p-cat').value);form.append('stock',document.getElementById('p-stock').value);selectedFiles.forEach(file=>form.append('images',file));await api('/api/admin/products',{method:'POST',body:form});modal.style.display='none';event.target.reset();selectedFiles=[];updatePreview();await loadProducts();}catch(error){alert(error.message);}finally{button.disabled=false;}});
if(location.pathname==='/admin'||location.pathname==='/admin.html'){loadAnalytics();loadProducts();loadOrders();}
